- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/pipeline.yml') }}"
    name: test

    url: http://44.192.116.23:8080/
    user: admin
    password: admin