- name: Create Folders in Jenkins
  community.general.jenkins_job:
    config: "{{ lookup('templates', 'folder.xml') }}"
    name: "{{item.name}}"
    url: "http://172.31.13.40:8080"
    user: "admin"
    token: "11f73e73eb52befc32e4d0aed578a10633"
  loop: "{{folders}}

