- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('templates', 'templates/pipeline.yml') }}"
    name: "test"

    url: http://44.192.116.23:8080/
    user: admin
    password: admin
  loop:
    - { jobName: "cart", folderName: "", repoName: "cart", componentName: "cart"}